### ISSUE TITLE
[requirement] Add a container able to build the documentation using mkdocs

### ISSUE THREAD

**Issue by cmoulliard** [vinzscam/backstage-chart#14]
## Description 

When we try to build the technical documentation using mkdocs, then the `plugin-techdocs-backend` reports the following error
```
2022-03-03T14:32:58.733Z techdocs error Failed to build the docs page: Failed to generate docs from ${inputDir} into ${outputDir}; caused by Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock Failed to generate docs from ${inputDir} into ${outputDir}; caused by Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock type=plugin name=Error cause=Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock stack=Error: Failed to generate docs from ${inputDir} into ${outputDir}; caused by Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock
    at _TechdocsGenerator.run (/app/node_modules/@backstage/techdocs-common/dist/index.cjs.js:312:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DocsBuilder.build (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:136:5)
    at async DocsSynchronizer.doSync (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:214:23)
    at async /app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:305:7
```
as backstage backend is running as a pod within a cluster and has no access to a container engine such as docker.

## Proposition

Add a container to the deployment YAML of backstage able to run Docker in Docker - [dind-rootless](https://docs.docker.com/engine/security/rootless/) 

Example:
```
spec:
  template:
    spec:
      containers:
      - command:
        - dockerd      
        - --host
        - tcp://127.0.0.1:2375
        image: registry.harbor.10.0.77.176.nip.io:32443/tap/dind-rootless
        imagePullPolicy: IfNotPresent
        name: dind-daemon
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /output
          name: output
      - name: backstage
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /output
          name: output
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: output
```
