### ISSUE TITLE
[feature] Ability to add addition Volumes

### ISSUE THREAD

**Issue by SimulatedGREG** [vinzscam/backstage-chart#15]
The ability to add additional Volumes to the backstage pod would allow for several things, but my immediate request would be for writing a GitHub App credentials file from a Secret.

**Comment by vinzscam** [comment]
I think you should be able to do this using https://github.com/vinzscam/backstage-chart#pass-extra-configuration-files
If you create a new configmap containing:

```yaml
integrations:
  github:
    - host: github.com
      apps:
        - appId: app id
           allowedInstallationOwners: ['GlobexCorp']
           clientId: client id
           clientSecret: client secret
           ...
```

or creating a configmap that looks like

```yaml
integrations:
  github:
    - host: github.com
      apps:
        - appId: ${GITHUB_APP_ID}
           allowedInstallationOwners: ['GlobexCorp']
           clientId: ${GITHUB_CLIENT_ID}
           clientSecret: ${GITHUB_CLIENT_SECRET}
           ...
```

and then store the environment variables as secret as described  [here](https://github.com/vinzscam/backstage-chart#sensitive-environment-variables)
