### ISSUE TITLE
Add some input validations to check if a container image is declared

### ISSUE THREAD

**Issue by cmoulliard** [vinzscam/backstage-chart#16]
## Issue

When we use the default chart's values and that we install the helm chart, then the process will fail as no default `image` is declared within the [values.yaml ](https://github.com/vinzscam/backstage-chart/blob/main/charts/backstage/values.yaml#L87-L91)file 
```
backstage:
  image:
    registry: ""
    repository: ""
    tag: ""
```

Example of test
```
helm template --dry-run --debug my-release backstage/backstage
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /Users/cmoullia/Library/Caches/helm/repository/backstage-0.3.0.tgz

---
# Source: backstage/templates/backstage-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-backstage
  namespace: "default"
  labels:
    app.kubernetes.io/name: backstage
    helm.sh/chart: backstage-0.3.0
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backstage
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/component: backstage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backstage
        helm.sh/chart: backstage-0.3.0
        app.kubernetes.io/instance: my-release
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: backstage
    spec:
      volumes:
      containers:
        - name: backstage-backend
          image: : ### EMPTY IMAGE NAME
          imagePullPolicy: "Always"
          command:
            - node
            - packages/backend
```

That will work if we execute this command
```
helm template --dry-run --debug my-release backstage/backstage \
  --set backstage.image.repository=backstage \
  --set backstage.image.registry=docker.io \
  --set backstage.image.tag=1.0
```

## Proposition

We should add some helm input validation as described [here](https://austindewey.com/2018/12/28/helm-tricks-input-validation-with-required-and-fail/) or as reported by the [helm doc](https://v2.helm.sh/docs/developing_charts/#using-the-required-function)

_Originally posted by @cmoulliard in https://github.com/vinzscam/backstage-chart/issues/13#issuecomment-1179130249_
