### ISSUE TITLE
Populate an ingress resource to expose the backend and/or front end service

### ISSUE THREAD

**Issue by cmoulliard** [vinzscam/backstage-chart#5]
## Requirement

Populate an ingress resource to expose the backend and/or front end service. Here is an idea of such a code implementation
https://raw.githubusercontent.com/backstage/backstage/master/contrib/chart/backstage/templates/ingress.yaml.

**Comment by cmoulliard** [comment]
If I create an ingress resource, then I can access the Service but I will got an error HTTP 503 as I think the frontend is not deployed

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: backstage.192.168.1.90.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-backstage
                port:
                  number: 80
```
So, that reminds me the question I asked on backstage about how to package app + backend together - see [here](https://github.com/backstage/backstage/issues/11598)
